metadata_directory: metadata
services:
  hasura:
    environment:
      hasura_graphql_enable_remote_schema_permissions: false
  postgres:
    environment:
      postgres_password: postgres
      postgres_user: postgres
storage:
  force_download_for_content_types: text/html,application/javascript
version: 3